
// place in a db so we don't have to resubmit the skill each time there are edits.

var descriptions = {

  "btcusd" : `<say-as interpret-as="spell-out">btcusd</say-as>, Bitcoin is the most well known of the crypto currencies. it is a type of digital currency in which encryption techniques, are used to regulate the generation of units, of currency and verify the transfer of funds. operating independently of a central bank.`,

  "ethusd" : `<say-as interpret-as="spell-out">ethusd</say-as>,Ethereum is a decentralized platform that runs smart contracts. smart contracts are applications that run exactly as programmed, without any possibility of downtime, censorship, fraud or third party inter fearence.  These applications run on a custom built blockchain, an enormously powerful shared global infrastructure, that can move value around and represent the ownership of property. This enables developers to create markets, store registries of debts or promises. move funds in accordance with instructions given, long in the past. like a will or a futures contract. and many other things that have not yet been invented. all without a middleman or counterparty risk.`,

  "ltcusd" : `<say-as interpret-as="spell-out">ltcusd</say-as>,Litecoin is a peer to peer Internet currency that enables instant near zero, cost payments to anyone in the world. Litecoin is an open source, global payment network, that is fully decentralized without any central authorities. Mathematics secures the network, and empowers individuals to control their own finances. Litecoin features faster transaction confirmation times, and improved storage efficiency, than the leading math based currency. With substantial industry support, trade volume and liquidity. Litecoin is a proven medium of commerce, complementary to Bitcoin.`,

  "aidusd" : `<say-as interpret-as="spell-out">aidusd</say-as>,AidCoin is the <say-as interpret-as="spell-out">ERC</say-as> 20 token that aims to become the preferred method to donate transparently through the Ethereum blockchain and to access the ecosystem of services provided by the AID Chain platform. The adoption of crypto currencies will impact the way we donate in the future, and Aid Coin is poised to play a leading role in this new era of fundraising.`,

  "avtusd" : `<say-as interpret-as="spell-out">avtusd</say-as>,Aventus is an Ethereum based platform. Its economic model eliminates uncontrolled resale and counterfeit tickets. It allows event organizers to create, manage and promote their events and tickets with dramatically reduced costs, even letting them set price controls and receive commissions on ticket resales. It also gives ticket buyers rewards for promoting events, and identifying fraudulent activity.`,
  
  "batusd" : `<say-as interpret-as="spell-out">batusd</say-as>,Basic Attention Token radically improves the efficiency of digital advertising by creating a new token that can be exchanged between publishers, advertisers, and users. It all happens on the Ethereum blockchain. The token can be used to obtain a variety of advertising and attention based services on the Brave platform. The utility of the token is based on user attention, which simply means a person’s focused mental engagement.`,

  "bchusd" : `<say-as interpret-as="spell-out">bchusd</say-as>,Bitcoin Cash brings sound money to the world, fulfilling the original promise of Bitcoin as Peer to Peer Electronic Cash. Merchants and users are empowered with low fees and reliable confirmations. The future shines brightly with unrestricted growth, global adoption, permissionless innovation, and decentralized development.`,

  "btgusd" : `<say-as interpret-as="spell-out">btgusd</say-as>,Bitcoin Gold decentralizes mining by adopting a <say-as interpret-as="spell-out">PoW</say-as> algorithm, Equihash, which cannot be run faster on the specialty equipment used for Bitcoin mining, ASIC miners. This gives ordinary users a fair opportunity to mine with ubiquitous G. P. U's. Bitcoin Gold is a free open source software project that is built by volunteer developers, and supported by a rapidly growing community of Bitcoin enthusiasts, that stretches around the globe.`,

  "dshusd" : `<say-as interpret-as="spell-out">dshusd</say-as>,At Dash’s core is a unique fully incentivized peer to peer network. Miners are rewarded for securing the blockchain and masternodes are rewarded for validating, storing and serving the blockchain to users. Master nodes represent a new layer of network servers that work in highly secure clusters called quorums. to provide a variety of decentralized services, like instant transactions, privacy and governance. while eliminating the threat of low cost network attacks.`,

  "dtausd" : `<say-as interpret-as="spell-out">dtausd</say-as>,Streamr provides a complete system to create unstoppable real time data apps, even without writing code. Currently, the valuable data you produce is at the mercy of large corporations. In the Streamr network, it’s yours to use and sell as you wish, and travels through a decentralised peer to peer network controlled by no one and incentivized by the DATA coin token.`,

  "edousd" : `<say-as interpret-as="spell-out">edousd</say-as>,Eidoo is a blockchain to human interface simplifying the interaction between the blockchain and its users.  The purpose of Eidoo is not only to accomplish things that others do not, but to do it in a different way, through a safer and simpler method, maintaining a special focus on the user experience and enabling the complexity of the crypto world to be more understandable. As safe as a decentralized exchange, as fast as a centralized one. The exchange manager does not have any access to the user accounts. The user enjoys a trading experience with some of the most competitive fees on the market. issue me another command`,

  "elfusd" : `<say-as interpret-as="spell-out">elfusd</say-as>, elf is a decentralised, self evolving, cloud computing network, providing a highly efficient multi chain parallel processing system, with cross chain communication and self evolving governance, in order to establish a block chain infrastructure suitable for commercial requirements of maintaning and exchanging crypto currencies. The service brings three innovations. scalable nodes across clusters of computers, resource isolation for smart contracts, and voting through token holders. .`,

  "eosusd" : `<say-as interpret-as="spell-out">eosusd</say-as>,a new blockchain architecture designed to enable vertical and horizontal scaling of decentralized applications. This is achieved by creating an operating system like construct upon which applications can be built. The software provides accounts, authentication, databases, asynchronous communication, and the scheduling of applications across many <say-as interpret-as="spell-out">CPU</say-as> cores or clusters. The resulting technology is a blockchain architecture that may ultimately scale to millions of transactions per second, eliminates user fees, and allows for quick and easy deployment and maintenance of decentralized applications, in the context of a governed blockchain.`,

  "etcusd" : `<say-as interpret-as="spell-out">etcusd</say-as>,Ethereum Classic is a decentralized platform that runs smart contracts: applications that run exactly as programmed without any possibility of downtime, censorship, fraud or third party interference. Ethereum Classic is a continuation of the original Ethereum blockchain, the classic version preserving untampered history; free from external interference and subjective tampering of transactions.`,

  "etpusd" : `<say-as interpret-as="spell-out">etpusd</say-as>,, Meta verse is trying to combine the advantages of Bit coin, Ethereum and Bit shares, while also including the functionalities of Chain link and Civic. A well designed smart contracs from Ethereum and easy to use asset creation, distribution and sharing from Bit shares. The project aims to deliver their own smart contract network connected to an oracle intermediary. oracles reliably feed information of the outside world into the block chain and make it accessible by smart contracts, while simultaneously running an asset sharing Exchange that can also host initial coin offerings, with an identity confirmation service. This makes it easier for everyone to host their own initial coin offerings, because they don’t have to undergo an extensive vetting process, the platform does it for them. And by doing so it becomes extremely promising for countries that have know your customer rules`,

  "funusd" : `<say-as interpret-as="spell-out">funusd</say-as>,,Using a powerful combination of peer to peer networking and cryptography. FunFair's advanced blockchain powered casino platform is the first to deliver secure and fair games for players, with easier set up and much lower cost, helping to create and empower a new breed of operators.`,

  "gntusd" : `<say-as interpret-as="spell-out">gntusd</say-as>,Golem is a global, open source, decentralized supercomputer, that anyone can access. It is made up of the combined power of users machines. from PCs to entire data centers.  Golem is capable of computing a wide variety of tasks, from CGI rendering, through machine learning, to scientific computing. Golem’s limitations are only defined by our developer community’s creativity. Golem creates a decentralized sharing economy of computing power, and supplies software developers with a flexible, reliable and cheap source of computing power.`,

  "itausd" : `<say-as interpret-as="spell-out">itausd</say-as>,The main innovation behind eye o ta is the Tangle. a revolutionary new blockless distributed ledger which is scalable, lightweight. for the first time it is possible to transfer value without any fees. Contrary to today’s Blockchains, consensus is no longer decoupled, but instead an intrinsic part of the system. leading to decentralized and self regulating peer to peer network. For the first time ever true micro, and even nano transactions are enabled due to the unique eye o ta Tangle architecture, providing developers with a brand new set of tools for their applications in both <say-as interpret-as="spell-out">IoT/say-as> and Web.`,

  "mnausd" : `<say-as interpret-as="spell-out">mnausd</say-as>,Decentraland is a virtual platform owned by its users.  Grab a VR headset or use your web browser and become completely immersed in a 3D, interactive world There are plenty of opportunities to explore or even create your own piece of the universe. Here, you can purchase land through the Ethereum blockchain, creating an immutable record of ownership. No one can limit what you build. With full control over your land, you can create unique experiences unlike anything in existence. Your imagination is the limit: go to a casino, watch live music, attend a workshop, shop with friends, start a business, test drive a car, visit an underwater resort, and much, much more—all within a 360 degree, virtual world.`,

  "neousd" : `<say-as interpret-as="spell-out">neousd</say-as>,knee o is a blockchain platform and cryptocurrency designed to build a scalable network of decentralized applications. The base asset of the NEO blockchain is the non divisible NEO token which generates GAS tokens that can be used to pay for transaction fees, generated by applications on the network. knee o supports a wide variety of commonly used programming languages such as Javascript, and see plus plus, by using a customized version of Docker, called knee oh <say-as interpret-as="spell-out">VM</say-as> that compiles the code into a secure executable environment`,

  "omgusd" : `<say-as interpret-as="spell-out">omgusd</say-as>,OmiseGO is an open payment platform and decentralised exchange issued on Ethereum, an open source public blockchain. It's slogan is Un bank the Banked and the stated objective is to provide better financial services for everyone. including both people who use traditional banking services, and people in developing countries and locales, which lack traditional banking infrastructure. Its token <say-as interpret-as="spell-out">OMG</say-as> is currently the sixth highest market cap Ethereum project in the world, and was the first Ethereum project to exceed $1,000,000,000 valuation. The project is supported by co founders of Ethereum.`,

  "qtmusd" : `<say-as interpret-as="spell-out">qtmusd</say-as>,Qtum is an open source Blockchain project that is developed by the Singapore based <say-as interpret-as="spell-out">qtum</say-as> Foundation. <say-as interpret-as="spell-out">qtum</say-as> is a hybrid blockchain application platform. <say-as interpret-as="spell-out">qtum</say-as> core technology combines a fork of bitcoin core, an Account Abstraction Layer allowing for multiple Virtual Machines including the Ethereum Virtual Machine <say-as interpret-as="spell-out">evm</say-as> and Proof of Stake consensus aimed at tackling industry use cases. We believe this will allow Smart Contracts and Decentralized Applications to run on a familiar foundation, while offering a robust environment for developers.`,

  "qshusd" : `<say-as interpret-as="spell-out">qshusd</say-as>,QUOINE LIQUID brings liquidity to the cryptocurrency space by providing a means for you to easily buy cryptocurrency with and cash out to fiat. Currently, each crypto exchange has its own level of liquidity that differs between the trading pairs it offers. This creates individual silos that may have great liquidity on one exchange but not on another. The LIQUID platform connects these silos into one combined pool to give you the greatest liquidity possible. To do this, QUOINE LIQUID encompasses two main offerings.`,

  "rcnusd" : `<say-as interpret-as="spell-out">rcnusd</say-as>,The REcoin tokens are designed to facilitate ​​a ​​wide​​r ange​​ of ​​financial ​​transactions​, which is supported by Hedging of <say-as interpret-as="spell-out">re</say-as> coin by real estate investments in countries with developed ​​and ​​stable economies ​such as the United States, Canada, the U. K. , Switzerland, Japan. A steadily developing ecosystem features partnerships with various internet platforms improving <say-as interpret-as="spell-out">re</say-as> coin’s liquidity.REcoin smart contracts, which is an online legal instrument simplifying and expediting real estate transactions. <say-as interpret-as="spell-out">re</say-as>coin holders have the unique opportunity to take part in decision making about the support and development of <say-as interpret-as="spell-out">re</say-as>coin by joining the membership club. Powered by blockchain technology offering stability and a superior way of payment for transactions and storing savings.`,

  "repusd" : `<say-as interpret-as="spell-out">repusd</say-as>,aweger is a decentralised prediction market which can forecast the outcome of an event based on the wisdom of the crowd principle. With this method, information collected from the crowd is averaged into the most realistic possibility and therefore the most probable outcome. Correct predictions are rewarded by the network, while incorrect reporting is penalised   this incentivises truthful reporting. The aweger aims to revolutionize prediction markets, and, in doing so, changing the way people receive and verify truth. The main idea is to make more accurate predictions by large groups of people, rather than a small team of experts.`,

  "rlcusd" : `<say-as interpret-as="spell-out">rlcusd</say-as>,i Exec provides distributed applications running on the blockchain a scalable, secure and easy access to the services, data sets, and computing resources they need. The technology relies on Ethereum, which allows us to build a virtual Cloud infrastructure that provides high performance computing services on demand. An innovative market network where everyone can monetize their applications, servers and data sets. As a Developer, you can use i Exec to overcome blockchain limitations, by executing your computations on a new distributed infrastructure. As a Provider, you can lend your machine power and monetize it by executing developer applications. As an Investor, you can get into the world of crypto economy by holding or trading your RLC tokens whenever you want.`,

  "sanusd" : `<say-as interpret-as="spell-out">sanusd</say-as>,Sentiment is all about measuring crowd moods so that you can make ideal trading decisions. Every datafeed Sentiment produces, either contributes or gives insight into crowd sentiment, and you can make this data work for you. Sentiment generates revenue with a regular subscription fees. Our token, the Sentiment Network Token, is used for accessing content and datafeeds. It can either be staked, giving holders limited access to services for free, or it can be spent in auctions to purchase our most exclusive data. This connects the SAN token value directly to the value of datafeeds and information Sentiment produces.`,

  "sngusd" : `<say-as interpret-as="spell-out">sngusd</say-as>,SnowGem maintains that there is no central authority, the system’s decisions will be controlled by nodes in the network. The network is open to anyone, anywhere in the world. We are looking forward to a future where transferring money is no longer complicated and troublesome. Snow Gem solves the problem of privacy by using shielded transactions, to hide information about the sender, the recipient, as well as the value on each transaction. You can now be assured that your financial information is private. Snow Gem is the first Equihash Master node system. Master nodes help us to achieve faster and more private transactions.Snow Gem will be implemented with incentive programs that will bring you profit by owning Snow Gem. We value our community and your participation will not only be appreciated, but also rewarded.`,

  "sntusd" : `<say-as interpret-as="spell-out">sntusd</say-as>,The Teller Network allows Stakeholders in the Network to find nearby users to exchange their cash, for digital assets and currency. giving any smar phone owner in the world, the ability to take control of their personal wealth. In this sense, Status becomes a piece of a Web banking infrastructure and creates a global, people as a ATM network. This has particular utility in developing markets where cash  based economies are prevalent and credit card penetration remains low. tackling the famous last mile of the remittance market`,

  "spkusd" : `<say-as interpret-as="spell-out">spkusd</say-as>,SpankChain is ​an ​adult ​entertainment ​ecosystem ​powered ​by blockchain ​technology. The ​Spank Chain ​ecosystem ​possesses ​a tiered ​architecture ​featuring ​three ​layers. Spank Chain ​Core, ​Spank Chain ​Services, ​and ​Spank Chain ​Applications. Spank Chain ​Core is ​comprised ​of ​smart ​contracts ​and ​tooling ​which ​provide ​the foundational ​functionalities ​necessary ​to ​operate ​a ​streaming ​or static ​content ​distribution application, ​namely ​a ​user ​profile ​system ​and ​payment ​capabilities. The ​Spank Chain ​Services ​layer contains ​a ​suite ​of ​ancillary ​services ​which ​add ​enhanced functionality ​to ​applications ​built ​upon ​Spank Chain ​Core, ​including payment ​channel ​hubs, age ​verification, ​live ​video, ​an ​ad ​network, ​an ​affiliate ​network, ​indexing, search, ​and ​an interface builder.`,

  "tnbusd" : `<say-as interpret-as="spell-out">tnbusd</say-as>, time new bank is a precision time value transmission platform based on blockchain technology, to organize a comprehensive network, comprised of primary, secondary and third market for time commodity exchange. M.I.T aims to deliver a standardized system that fully expresses the value of time commodities based on how time exporters are recognized, and demanded via a scientific and systematic analytical model, by leveraging its decentralized value transmission platform. In commodity value transmission process, T. N. B. will be adopted as the settlement currency to accurately tell both the current and future value of the time commodities. Under the above mentioned structure, time demanders, can quickly retrieve, on the M.I.T platform, to position and purchase the exact time commodity from the exact time exporter. After completing the purchase, time demanders could either materialize the time commodities, or transfer them on the secondary market. Investors can invest on commodities via the third market. In this way, multiple layers of demand are fulfilled.`,

  "trxusd" : `<say-as interpret-as="spell-out">trxusd</say-as>, Tron is a block chain based protocol for a free content entertainment system, allowing  each user to freely publish, store and own data. and in the decentralized autonomous form, decides the distribution, subscription and push of contents. and enables content creators by releasing, circulating and dealing with digital assets. thus forming a decentralized content entertainment ecosystem. Tronix is an <say-as interpret-as="spell-out>erc</say-as> 20 token based on the Ethereum blockchain, acting as the basic unit of account on the platform. `,

  "xmrusd" : `<say-as interpret-as="spell-out">xmrusd</say-as>,Monero is a crypto night algorithm based alternative crypto currency. The coin is based on Proof of Work, and has a block reward that varies smoothly. The difficulty retargets every block with a sixty second block target. Monero uses a Ring Signature system to protect your privacy, allowing users to make untraceable transactions.`,

  "xrpusd" : `<say-as interpret-as="spell-out">xrpusd</say-as>,Ripple is more known for its digital payment protocol than its cryptocurrency, XRP. Ripple operates on an open source and peer to peer decentralized platform, that allows for a seamless transfer of money in any form, whether USD, Yen, lite coin, or bit coin. The digital currency, X.R.P., acts as a bridge currency to other currencies. It does not discriminate between one fiat crypto currency and another, and thus, makes it easy for any currency to be exchanged for another.`,

  "yywusd" : `<say-as interpret-as="spell-out">yywusd</say-as>,being the fundamental crypto in YOYO content ecosystem. YOYO is utilized for buying advertising, service, and applied as a transaction tool. With the development of the YOYO network, the demand of YOYO will rise as well. YOYO adopts the algorithm of P. O. T. Proof of Taste, to reward content creators, spreaders, and the third party systems. All the benefits of peer to peer blockchain technology, namely distributed, security, privacy protection, and complete control by users, are incorporated in YOYO.`,

  "zecusd" : `<say-as interpret-as="spell-out">zecusd</say-as>,zcash is a cryptocurrency aimed at using cryptography to provide enhanced privacy for its users compared to other cryptocurrencies such as bit coin. As a result, zcash payments are published on a public blockchain, but users are able to use an optional privacy feature, to conceal the sender, recipient, and amount being transacted. Like bit coin, zcash has a fixed total supply of 21 million units.In addition, zcash gives the trans actors the option of selective disclosure, that allows a user to provide proof of payment for auditing and regulatory purposes.`,

  "zrxusd" : `<say-as interpret-as="spell-out">zrxusd</say-as>,0x is an open protocol that is designed to offer a decentralized exchange as part of the Ethereum blockchain. 0x is made using a protocol that involves Ethereum smart contacts, that allow those around the world, to run a decentralized exchange. The team behind 0x strongly believes that in the future, you will find thousands of tokens from Ethereum, and that 0x can provide an efficient, and trustworthy way to exchange them. 0x is designed to be different from both centralized and decentralized exchanges, providing the best possible combination of features.`,

};
module.exports = descriptions;